# test data
NUM_COURSE_CODES = 86
NUM_PROGRAMS_MAJORS = 159
TEST_DICT = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 2020
}
TEST_FILENAME = "test.json"
COURSES_CONSTANT = "courses"

TEST_COURSE_CODE = "acct"
TEST_COURSE_CODE_AGR = "agr"
TEST_COURSE = [TEST_COURSE_CODE, TEST_COURSE_CODE_AGR]

TEST_PROGRAM_NAME = "ahn"
TEST_MAJOR_NAME = "Applied Human Nutrition"
TEST_MAJOR_REQ = "CHEM*1040"
TEST_PROGRAM = [TEST_PROGRAM_NAME, TEST_MAJOR_NAME, TEST_MAJOR_REQ]